version: '3.8'

services:
  # PocketBase Backend
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: myrecipebox-pocketbase
    restart: unless-stopped
    command: >
      --serve --http=0.0.0.0:8090 
      --dir=/pb_data 
      --publicDir=/pb_public
    ports:
      - "8090:8090"
    volumes:
      - pocketbase_data:/pb_data
      - pocketbase_public:/pb_public
      - ../pocketbase/pb_migrations:/pb_migrations:ro
    environment:
      - PB_ADMIN_EMAIL=${PB_ADMIN_EMAIL}
      - PB_ADMIN_PASSWORD=${PB_ADMIN_PASSWORD}
      - PB_ENCRYPTION_KEY=${PB_ENCRYPTION_KEY}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8090/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - recipe_network

  # SvelteKit Frontend
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
      args:
        - NODE_ENV=production
        - VITE_POCKETBASE_URL=${VITE_POCKETBASE_URL}
        - VITE_GEMINI_API_KEY=${VITE_GEMINI_API_KEY}
    container_name: myrecipebox-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      pocketbase:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - VITE_POCKETBASE_URL=${VITE_POCKETBASE_URL}
    networks:
      - recipe_network


volumes:
  pocketbase_data:
    driver: local
  pocketbase_public:
    driver: local

networks:
  recipe_network:
    driver: bridge