services:
  # PocketBase Backend
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: myrecipebox-pocketbase
    restart: unless-stopped
    command: serve --http=0.0.0.0:8090 --dir=/pb_data --publicDir=/pb_public --migrationsDir=/pb_migrations
    ports:
      - "8090:8090"
    volumes:
      - pocketbase_data:/pb_data
      - pocketbase_public:/pb_public
      - ../pocketbase/pb_migrations:/pb_migrations:ro
    environment:
      - PB_ADMIN_EMAIL=${PB_ADMIN_EMAIL:-admin@example.com}
      - PB_ADMIN_PASSWORD=${PB_ADMIN_PASSWORD:-password123}
      - PB_ENCRYPTION_KEY=${PB_ENCRYPTION_KEY:-your-32-char-encryption-key-here}
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8090 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 20s
    networks:
      - recipe_network

  # SvelteKit Frontend
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
      args:
        - NODE_ENV=production
        - VITE_POCKETBASE_URL=${VITE_POCKETBASE_URL:-http://pocketbase:8090}
        - VITE_GEMINI_API_KEY=${VITE_GEMINI_API_KEY}
    container_name: myrecipebox-frontend
    restart: unless-stopped
    ports:
      - "3001:3000"
    depends_on:
      pocketbase:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - VITE_POCKETBASE_URL=${VITE_POCKETBASE_URL:-http://pocketbase:8090}
    networks:
      - recipe_network


volumes:
  pocketbase_data:
    driver: local
  pocketbase_public:
    driver: local

networks:
  recipe_network:
    driver: bridge